# Android React Native
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pwd'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -a && cd src && ls -a'

# - task: NodeTool@0
#   inputs:
#     versionSpec: '6.x'

# - task: Npm@1
#   inputs:
#     command: 'install'
#     workingDir: '$(Build.SourcesDirectory)/react-native-pipeline'
# - task: Gradle@2
#   inputs:
#     workingDirectory: '$(Build.SourcesDirectory)/android'
#     gradleWrapperFile: '$(Build.SourcesDirectory)/android/gradlew'
#     gradleOptions: '-Xmx3072m'
#     publishJUnitResults: false
#     testResultsFiles: '**/TEST-*.xml'
#     tasks: 'assembleDebug'
# - task: AndroidSigning@3
#   inputs:
#     apkFiles: '**/*.apk'
#     apksign: false
